CREATE TABLE quests (
	id VARCHAR NOT NULL PRIMARY KEY,
	artist VARCHAR NOT NULL,
	poem VARCHAR NOT NULL,
	next VARCHAR
);

CREATE TABLE images (
	id INTEGER NOT NULL PRIMARY KEY,
	quest_id VARCHAR NOT NULL REFERENCES quests(id) ON DELETE CASCADE,
	data BLOB NOT NULL
);